version: '3'

services:
  zookeeper:
    image: zookeeper:3.6.3
    volumes:
      - ./zk/data:/data
    ports:
      - 2182:2181

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 172.26.23.199
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "oms_order:2:1"   #kafka启动后初始化一个有2个partition(分区)1个副本名叫oms_order的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka/logs:/kafka/logs
    depends_on:
      - zookeeper